### ISSUE TITLE
Missing python script. 

### ISSUE THREAD

**Issue by tirohia** [Oshlack/Toblerone#1]
Mōrena. 

The usage documentation suggests the use of a python script (make_bedfiles.py) to generate Bed files, but it doesn't appear to be included in the repository. Wondering if you might have that available somewhere? 

Thanks.
Ben.

**Comment by lonsbio** [comment]
Thanks for your interest in Toblerone Ben! I just noticed that too, script didn't make it across from the development repository. I'm updating the repository shortly, and will include.

**Comment by tirohia** [comment]
Excellent, ta muchly. Will let you know how it goes when I get it all running.

**Comment by lonsbio** [comment]
Apologies for the non-standard use of the word "shortly". The missing script is there now.
